<a href="https://colab.research.google.com/github/rmatuk/RNCACIC2023/blob/main/RN_Practica0_CACIC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CACIC 2023
# Tutorial Python & Numpy

**Introducción**

Este tutorial es una introducción amigable al lenguaje de programación Python, y a la librería de procesamiento científico Numpy.

**Para poder modificar y/o correr el código, desde su Google Colab, ábranlo en modo Playground, o hagan una copia de esta Jupyter Notebook a su Drive (File/Save a copy in Drive...). También si lo desean, pueden bajar el código de la Jupyter Notebook, y correrlo en forma local en sus computadoras, tras instalar Python, Numpy, Matplotlib, y Jupyter Notebook.**

**Tareas:**

* Leer el tutorial.
* Hacer los ejercicios intercalados en el tutorial.
* Modificar el código del tutorial, para experimentar con los ejemplos.

##Introducción

Python es un lenguaje de programación de propósito general, que posee algunas librerías (numpy, scipy, matplotlib) que lo hacen muy poderoso para su uso en computación científica.

Para los que ya posean experiencia previa en Matlab, una página recomendable que también pueden consultar es: https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html

En este tutorial, cubriremos los siguientes temas:

* Python Básico: Tipos de datos básicos (Contenedores: Listas, Diccionarios, Conjuntos, Tuplas), Funciones, Clases
* Numpy: Arrays, Indexado, Tipos de datos, Broadcasting
* Matplotlib: Ploteo, Subplots, Imágenes

##Conceptos básicos de Python

Python es un lenguaje de programación de alto nivel, dinámicamente tipado. Frecuentemente se dice que el código en Python es casi como un *pseudocódigo*, ya que permite expresar ideas muy poderosas en muy pocas líneas de código, siendo al mismo tiempo muy legible. Como ejemplo, acá hay una implementación del clásico algortimo de quicksort en Python:

**NOTA**: En IPython, el código en una celda se ejecuta cliqueando dentro de la celda, y presionando **Shift+Enter** al mismo tiempo.

In [ ]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print(quicksort([3,6,8,10,1,2,1]))

###Versiones de Python

Actualmente hay dos versiones soportadas estables de Python, 2.7 y Python 3. Python 3.0 introdujo algunos cambios incompatibles con Python 2, y entonces algunos códigos escritos para 2.7 podrían no funcionar para 3, y viceversa. Para esta clase, usaremos Python 3.

Para ver la versión de Python que está instalada en su computadora ejecutar en línea de comando `python --version`.

### Ejecutando línea de comando desde Jupyter Notebook

En la interfaz web de Jupyter Notebook, para ejecutar y ver la salida de una instrucción a línea de comando de la computadora, anteponer el símbolo: !

In [ ]:
# Muestra el directorio actual
!pwd

# TAREA: mostrar desde Jupyter la versión de Python que tiene instalado el sistema
print("########### REEMPLAZAR POR TU CODIGO ############")




###Tipos de datos básicos

####Números

Los enteros y los floats se comportan en la forma habitual de los lenguajes de programación:

In [ ]:
x = 3
print (x, type(x))

In [ ]:
print (x + 1)   # Suma;
print (x - 1)   # Resta;
print (x * 2)   # Multiplicación;
print (x ** 2)  # Exponencial;

In [ ]:
x += 1     # Incrementa la variable x en 1 y se la asigna a sí misma
print (x)  # Imprime "4"
x *= 2     # Duplica el valor de la variable x, y se la asigna a sí misma
print (x)  # Imprime "8"

In [ ]:
y = 2.5
print (type(y)) # Imprime el tipo de la variable, en este caso "<type 'float'>"
print (y, y + 1, y * 2, y ** 2) # Imprime "2.5 3.5 5.0 6.25"

In [ ]:
#TAREA: Crear la variable z, y asignarle el triple del valor de la suma de x más y.
print("***********REEMPLAZAR POR TU CODIGO*************")

Notar que a diferencia de otros lenguajes, Python no tiene los operadores unarios de incremento (x++) o decremento (x--).

Python tiene también tipos para enteros long y números complejos; puede encontrar los detalles en [documentacion](https://docs.python.org/2/library/stdtypes.html#numeric-types-int-float-long-complex).

####Booleanos

Python implementa todos los operadores usuales de la lógica booleana, pero usa palabras en inglés en lugar de los símbolos (`&&`, `||`, etc.):

In [ ]:
t, f = True, False
print (type(t)) # Imprime "<type 'bool'>"

Ahora veamos algunas operaciones:

In [ ]:
print (t and f) # Logical AND;
print (t or f)  # Logical OR;
print (not t)   # Logical NOT;
print (t != f)  # Logical XOR;

####Strings

In [ ]:
hello = 'hello'   # Los strings pueden usar comillas simples
world = "world"   # o dobles
print (hello, len(hello))

In [ ]:
hw = hello + ' ' + world  # Concatenación de strings
print (hw)  # imprime "hello world"

In [ ]:
hw12 = ('%s %s %d' % (hello, world, 12))  # Formateando la salida
print (hw12)  # imprime "hello world 12"

Los strings tienen algunas funciones útiles; por ejemplo:

In [ ]:
s = "hello"
print (s.capitalize())  # Pone la primera letra mayúscula; imprime "Hello"
print (s.upper())       # Convierte un string a todas mayúsculas; imprime "HELLO"
print (s.rjust(7))      # Alinea a la derecha un string; imprime "  hello"
print (s.center(7))     # Alinea al centro un string; imprime " hello "
print (s.replace('l', '(ell)'))  # Reemplaza todas las instancias de un substring con otro;
                               # imprime "he(ell)(ell)o"
print ('  world '.strip())  # Quita los espacios en blanco al inicio y al final del string; imprime "world"

Puede encontrar una lista de todos los métodos para los strings en la [documentación](https://docs.python.org/2/library/stdtypes.html#string-methods).

###Containers

Python incluye varios tipos container: listas, diccionarios, conjuntos y tuplas.

####Listas

Una lista es el equivalente Python de un array, pero puede cambiar de tamaño y puede contener elementos de diferentes tipos:

In [ ]:
xs = [3, 1, 2]   # Crea una lista
print (xs, xs[2])
print (xs[-1])     # Los índices negativos cuentan desde el fin de la lista; imprime "2"

In [ ]:
xs[2] = 'foo'    # Listas pueden contener elementos de diferentes tipos
print (xs)

In [ ]:
xs.append('bar') # Agrega un elemento nuevo al final de la lista
print (xs)

In [ ]:
x = xs.pop()     # Remueve and devuelve el último elemento de la lista
print (x, xs)

Pueden consultar más detalles acerca de las listas en la [documentación](https://docs.python.org/2/tutorial/datastructures.html#more-on-lists).

####Slicing

Además de acceder un elemento de la lista por vez, en Python se pueden acceder a sublistas de la lista; esto se conoce como slicing:

In [ ]:
nums = range(5)    # range is una función que crea un rango de enteros de cero a n-1.
print (type(nums))
nums = list(nums) # Llamamos a list para convertir el tipo range a tipo lista, lo que se conoce como "casting".
print (type(nums))
print (nums)         # Imprime "[0, 1, 2, 3, 4]"
print (nums[2:4])    # Devuelve una sublista desde el índice 2 al 4 (exclusivo); imprime "[2, 3]"
print (nums[2:])     # Devuelve una sublista desde el índice 2 hasta el final; imprime "[2, 3, 4]"
print (nums[:2])     # Devuelve una sublista desde el comienzo al índice 2 (exclusivo); imprime "[0, 1]"
print (nums[:])      # Devuelve una sublista de toda la lista: imprime "[0, 1, 2, 3, 4]"
print (nums[:-1])    # Los índices de una sublista pueden ser negativos; imprime "[0, 1, 2, 3]"
nums[2:4] = [8, 9] # Asigna nuevos valores al slice
print (nums)         # Imprime "[0, 1, 8, 8, 4]"

####Loops

Se puede hacer un ciclo (loop) sobre los elementos de una lista de esta forma:

In [ ]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print (animal)

Para acceder al índice de cada elemento dentro del cuerpo del loop, se usa la función `enumerate`:

In [ ]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print ('#%d: %s' % (idx + 1, animal))

####Listas por comprensión:

Considere el siguiente ejemplo, que computa números al cuadrado:

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print (squares)

Podemos hacer más simple este código usando definición de listas por comprensión:

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print (squares)

Las listas por comprensión también pueden tener condiciones:

In [ ]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print (even_squares)

####Diccionarios

Un diccionario almacena pares (clave, valor) pairs, en forma similar a un `Map` en Java o a un objecto en Javascript. Por ejemplo:

In [ ]:
d = {'cat': 'cute', 'dog': 'furry'}  # Crea un diccionario nuevo con algunos datos
print (d['cat'])       # Toma una entrada de un diccionario; imprime "cute"
print ('cat' in d)     # Chequea si el diccionario tiene la clave dada; imprime "True"

In [ ]:
d['fish'] = 'wet'    # Setea una entrada en un diccionario
print (d['fish'])      # Imprime "wet"

In [ ]:
print (d['monkey'])  # KeyError: 'monkey' no es una clave de d

In [ ]:
print (d.get('monkey', 'N/A'))  # Toma un elemento con un default; imprime "N/A"
print (d.get('fish', 'N/A'))    # Toma un elemento con un default; imprime "wet"

In [ ]:
del d['fish']        # Remueve un elemento de un diccionario
print (d.get('fish', 'N/A')) # "fish" no es más una clave de d; imprime "N/A"

Podés encontrar toda la información acerca de los diccionarios en la [documentación](https://docs.python.org/2/library/stdtypes.html#dict).

Es fácil iterar sobre las claves de un diccionario:

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print ('A %s has %d legs' % (animal, legs))

Para acceder a las claves y sus valores correspondientes, usar el método items:

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
    print ('A %s has %d legs' % (animal, legs))

Diccionarios por comprensión: Similar a las listas por comprensión, pero para definir diccionarios. Por ejemplo:

In [ ]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print (even_num_to_square)

####Conjuntos (Sets)

Un conjunto es una colección de elementos distintos sin ningún orden. Por ejemplo:

In [ ]:
animals = {'cat', 'dog'}
print ('cat' in animals)   # Chequea si un elemento está en un conjunto; imprime "True"
print ('fish' in animals)  # imprime "False"


In [ ]:
animals.add('fish')      # Agrega un elemento a un conjunto
print ('fish' in animals)
print (len(animals))       # Numero de elementos en un conjunto

In [ ]:
animals.add('cat')       # Agregar al conjunto un elemento que ya está en él, no hace nada
print (len(animals))
animals.remove('cat')    # Remueve un elemento de un conjunto
print (len(animals))

_Loops_: Iterar sobre un conjunto tiene la misma sintaxis que sobre una lista; sin embargo, como los conjuntos no tienen orden, no se puede saber el orden en el cuál se visitarán los elementos del conjunto:

In [ ]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print ('#%d: %s' % (idx + 1, animal))

Definición de conjuntos por comprensión:

In [ ]:
from math import sqrt
print ({int(sqrt(x)) for x in range(30)})

####Tuplas

Una tupla es una lista inmodificable de valores. Las tuplas son similares a las listas, pero al ser inmutables, las tuplas pueden ser usadas como claves en los diccionarios, mientras que las listas no. Ejemplo:



In [ ]:
d = {(x, x + 1): x for x in range(10)}  # Crea un diccionario con claves tuplas
t = (5, 6)       # Crea una tupla
print (type(t))
print (d[t])
print (d[(1, 2)])

In [ ]:
t[0] = 1

###Funciones

En Python, las funciones son definidas usando la keyword `def`. Por ejemplo:

In [ ]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print (sign(x))

Frecuentemente se necesitan definir funciones que tomen argumentos opcionales. Ejemplo:

In [ ]:
def hello(name, loud=False):
    if loud:
        print ('HELLO, %s' % name.upper())
    else:
        print ('Hello, %s!' % name)

hello('Bob')
hello('Fred', loud=True)

###Clases

La sintaxis para definir clases en Python es la siguiente:

In [ ]:
class Greeter:

    # Constructor
    def __init__(self, name):
        self.name = name  # Crea una instancia de la variable

    # Un método de la clase
    def greet(self, loud=False):
        if loud:
            print ('HELLO, %s!' % self.name.upper())
        else:
            print ('Hello, %s' % self.name)

g = Greeter('Fred')  # Construye una instancia de la clase Greeter
g.greet()            # Llama al método de la clase; imprime "Hello, Fred"
g.greet(loud=True)   # Llama al método de la clase; imprime "HELLO, FRED!"

##Numpy

Numpy es la librería central para cómputo científico en Python (ver la documentación en [referencia](https://docs.scipy.org/doc/numpy-1.14.0/reference/)). Provee arrays multidimensionales de alta performance, y herramientas para trabajar con estos arrays. Para los que saben MATLAB, les puede ser útil este [tutorial](http://wiki.scipy.org/NumPy_for_Matlab_Users) para empezar con Numpy.

Para utilizar Numpy, lo primero que debemos hacer es importar el paquete `numpy`:

In [ ]:
import numpy as np

###Arrays

Un arreglo en numpy es una grilla de valores, todos del mismo tipo, y que está indexada por una tupla de enteros no negativos. El número de dimensiones es el rango del array; la forma del array es una tupla de enteros que nos da el tamaño del array a lo largo de cada dimensión.

Podemos inicializar numpy arrays con listas anidadas de Python, y acceder a sus elementos usando llaves cuadradas ([]):

In [ ]:
a = np.array([1, 2, 3])  # Crea un array de rango 1
print (type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Cambia un elemento del array
print (a)

In [ ]:
b = np.array([[1,2,3],[4,5,6]])   # Crea un array de rango 2
print (b)

In [ ]:
print (b.shape)
print (b[0, 0], b[0, 1], b[1, 0])

Numpy tiene además muchas funciones para crear arrays:

In [ ]:
a = np.zeros((2,2))  # Crea an array de todos ceros
print (a)

In [ ]:
b = np.ones((1,2))   # Crea un array de todos unos
print (b)

In [ ]:
c = np.full((2,2), 7) # Crea un array de valores constantes
print (c)

In [ ]:
d = np.eye(2)        # Crea una matrix identidad de 2x2
print (d)

In [ ]:
e = np.random.random((2,2)) # Crea un array de valores random
print (e)

###Array indexing

Numpy nos ofrece varias formas de indexar arrays.

Slicing: Como las listas en Python, los numpy arrays puede ser sliced. Como los arrays son multidimensionales, se debe especificar un slice para cada dimensión del array:

In [ ]:
import numpy as np

# Crea el siguiente array de rango 2 con dimensiones (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Usa slicing para extraer el subarray consistente de las dos primeras filas
# y las columnas 1 y 2; b es el siguiente array de dimensión (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print (b)

Atención: Un slice de un array es una vista a posiciones en memoria de los datos originales, y si modificamos el slice, modificamos los datos del array original.

In [ ]:
print (a[0, 1])
b[0, 0] = 77    # b[0, 0] apunta a la misma posición en memoria que a[0, 1]
print (a[0, 1])

Podés mezclar integer indexing con slice indexing. Sin embargo, esto nos dará un array de menor rango que el array original.

In [ ]:
# Crea un array de rango 2 array de forma (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (a)

Dos formas de acceder a los datos en la fila media del array.
Mezclar integer indexing con slices produce un array de menor rango, mientras que usar solo slices produce un array del mismo rango que el array original:

In [ ]:
row_r1 = a[1, :]    # Vista Rango 1 de la segunda fila de a
row_r2 = a[1:2, :]  # Vista Rango 2 de la segunda fila de a
row_r3 = a[[1], :]  # Vista Rango 2 de la segunda fila de a
print (row_r1, row_r1.shape)
print (row_r2, row_r2.shape)
print (row_r3, row_r3.shape)

In [ ]:
# Ejemplo accediendo a las columnas del array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print (col_r1, col_r1.shape)

print (col_r2, col_r2.shape)

Integer array indexing: Cuando se indexa los numpy arrays usando slicing, el array resultante será siempre un subarray del array original. Por el contrario, usar integer indexing permite construir arrays arbitrarios usando datos de otro array. Ejemplo:

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

# Un ejemplo de integer array indexing.
# El array resultado tiene forma (3,)
int_idx1 = a[[0, 1, 2], [0, 1, 0]]
print (int_idx1, int_idx1.shape)

# El ejemplo anterior es equivalente al siguiente:
int_idx2 = np.array([a[0, 0], a[1, 1], a[2, 0]])
print (int_idx2, int_idx2.shape)

In [ ]:
# Cuando se usa integer array indexing, se puede reusar el mismo
# elemento del array fuente:
print (a[[0, 0], [1, 1]])

# Equivalente al ejemplo anterior
print (np.array([a[0, 1], a[0, 1]]))

Integer array indexing también es útil para seleccionar o mutar un elemento de cada fila de una matriz:

In [ ]:
# Crea un array nuevo
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print (a)

In [ ]:
# Crea un array de indices
b = np.array([0, 2, 0, 1])

# Selecciona un elemento de cada fila de a usando los índices en b
print (a[np.arange(4), b])  # Imprime "[ 1  6  7 11]"

In [ ]:
# Muta un elemento de cada fila de a usando los índices en b
a[np.arange(4), b] += 10
print (a)

También se pueden seleccionar elementos de un array que satisfagan ciertas condiciones lógicas. Ejemplo:

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Encuentra los elementos de a que son más grandes que 2;
                    # returna un array numpy de Booleanos de la misma forma
                    # que a, donde cada posición de bool_idx dice
                    # si el elemento de a es > 2.

print (bool_idx)

In [ ]:
# Podemos usar el array de booleanos del ejemplo anterior, para construir un array
# que consista de los elementos de a que sean True en bool_idx
print (a[bool_idx])

# Se puede hacer todo lo anterior con un solo comando:
print (a[a > 2])

###Tipos de Datos

Un array numpy es una grilla de elementos del mismo tipo. Numpy intenta adivinar el tipo de datos cuando se crea el array, pero opcionalmente también se le puede especificar el tipo de datos. Ejemplo:

In [ ]:
x = np.array([1, 2])  # Numpy adivina el tipo de datos
y = np.array([1.0, 2.0])  # Numpy adivina el tipo de datos
z = np.array([1, 2], dtype=np.int64)  # Fuerza el tipo de datos

print (x.dtype, y.dtype, z.dtype)

###Operaciones matemáticas en Numpy

Las funciones matemáticas básicas operan elemento a elemento en el array, y están disponibles tanto como sobrecarga de operadores, y como funciones del módulo numpy:

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Suma elemento a elemento; son equivalentes.
print (x + y)           # Sobrecarga de operador
print (np.add(x, y))    # Función numpy

In [ ]:
# Resta elemento a elemento; son equivalentes.
print (x - y)
print (np.subtract(x, y))

In [ ]:
# Multiplicación elemento a elemento; son equivalentes.
print (x * y)
print (np.multiply(x, y))

In [ ]:
# División elemento a elemento; son equivalentes.
# Producen el siguiente array:
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print (x / y)
print (np.divide(x, y))

In [ ]:
# Raíz cuadrada elemento a elemento.
# Produce el siguiente array:
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print (np.sqrt(x))

Notar que `*` hace una multiplicación elemento a elemento. La función `dot` sirve para calcular productos internos de vectores, para multiplicar un vector por una matriz, y para multiplicar matrices. `dot` está disponible como una función del módulo numpy y como un método de instancia de los objetos array:

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Producto interno. Ambos producen 219
print (v.dot(w))
print (np.dot(v, w))

In [ ]:
# Producto Matrix / vector; ambos producen el array [29 67]
print (x.dot(v))
print (np.dot(x, v))

In [ ]:
# Producto matrix / matrix; ambos producen el array de rango 2
# [[19 22]
#  [43 50]]
print (x.dot(y))
print (np.dot(x, y))

Numpy provee muchas funciones útiles para hacer cómputos en arrays; una de las más útiles es
`sum`:

In [ ]:
x = np.array([[1,2],[3,4]])

print (np.sum(x))  # Computa la suma de todos los elementos; imprime "10"
print (np.sum(x, axis=0))  # Computa la suma de cada columna; imprime "[4 6]"
print (np.sum(x, axis=1))  # Compute la suma de cada fila; imprime "[3 7]"

Para transponer una matriz, usamos el atributo T del objeto array:

In [ ]:
print (x)
print (x.T)

In [ ]:
v = np.array([[1,2,3]])
print (v)
print (v.T)

La lista completa de funciones matemáticas de numpy se puede consultar en la [documentación](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

### Broadcasting

Broadcasting es un mecanismo poderoso que nos permite operar con arrays de diferentes formas. Frecuentemente tenemos un array más pequeño y un array más grande, y queremos utilizar el array más pequeño múltiples veces para hacer alguna operación sobre el array más grande.

Por ejemplo, supongamos que queremos sumar un vector constante a cada fila de una matriz:

In [ ]:
# Sumaremos el vector v a cada fila de la matriz x,
# almacenando el resultado en la matriz y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Crea una matriz vacía de la misma forma que x

# Suma el vector v a cada fila de la matriz x con un loop
for i in range(4):
    y[i, :] = x[i, :] + v

print (y)

Lo anterior funciona; sin embargo, cuando la matriz `x` es muy grande, computar con un loop explícito en Pyton puede ser muy lento. Notar que sumar el vector v a cada fila de la matrix `x` es equivalente a formar una matrix `vv` apilando múltiples copias de `v`, y haciendo luego una suma elemento a elemento de `x` y `vv`:

In [ ]:
vv = np.tile(v, (4, 1))  # Apilamos 4 copias de v
print (vv)               # Imprime "[[1 0 1]
                         #           [1 0 1]
                         #           [1 0 1]
                         #           [1 0 1]]"

In [ ]:
y = x + vv  # Suma x y vv elemento a elemento
print (y)

El broadcasting de Numpy nos permite realizar todo este cómputo sin la necesidad de crear múltiples copias de v. Considere esta nueva versión, usando broadcasting:

In [ ]:
import numpy as np

# Sumaremos el vector v a cada fila de la matriz x,
# almacenando el resultado en la matriz y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
print (x.ndim, x.shape) # Rango y forma
print (v.ndim, v.shape)
y = x + v  # Suma v a cada fila de x usando broadcasting
print (y)

El comando `y = x + v` funciona aunque `x` tenga forma `(4, 3)` y `v` tenga forma `(3,)` debido al broadcasting; este comando trabaja como si v tuviese la forma `(4, 3)`, donde cada fila es una copia de `v`, y la suma hubiese sido hecho elemento a elemento.

Reglas del Broadcasting:

1. Si los arrays no tienen el mismo rango, agrandar por adelante con 1s la forma del array de menor rango, hasta que ambos arrays tengan el mismo rango.
2. Dos arrays son compatibles en una dimension, si ellos tienen el mismo tamaño en esa dimensión, o si uno de los arrays tiene tamaño 1 en esa dimensión.
3. Los arrays pueden ser broadcasteados juntos si son compatibles en todas las dimensiones.
4. Después del broadcasting, cada array se comporta como si tuviese forma igual al máximo elemento de las formas en cada una de las dimensiones de los dos arrays de entrada.
5. En cualquier dimensión donde un array tuviese la forma 1 y el otro array tuviese forma mayor que 1, el primer array se comporta como si fuese copiado en esa dimensión.

Si no les queda muy claro el tema del broadcasting, lean la [documentación](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) o esta [explicación](http://wiki.scipy.org/EricsBroadcastingDoc).

Las funciones que soportan broadcasting son conocidas como funciones universales. Pueden encontrar la lista de todas las funciones universales en la [documentación](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Algunas aplicaciones del broadcasting:

In [ ]:
# Computar el producto externo de vectores
v = np.array([1,2,3])  # v tiene forma (3,) y rango 1
w = np.array([4,5])    # w tiene forma (2,) y rango 1
# Para computar el producto externo, primero cambiamos la forma de v a un vector
# columna de forma (3, 1), y entonces su rango ahora será 2. Cuando hacemos el
# broadcast contra w, w tiene rango 1. Entonces, como debe ser del mismo rango que v,
# w agrega 1s por delante a su forma, para alcanzar el rango 2, y será de la forma (1,2).
# Luego, ambos crecen para tener forma igual al máximo de los elementos en cada dimensión,
# y entonces ambos tendrán forma (3,2). Luego, v y w hacen multiplicación elemento a elemento,
# y se produce una salida de la forma (3, 2), que es el producto externo de v y w:

print (np.reshape(v, (3, 1)) * w)

In [ ]:
# Agregar un vector a cada fila de una matriz
x = np.array([[1,2,3], [4,5,6]])
# x tiene forma (2, 3) y v tiene forma (3,) así que ellos broadcastean a (2, 3):

print (x.shape)
print(v.shape)
print (x + v)

In [ ]:
# Sumar un vector a cada columna de una matriz
# x tiene forma (2, 3) y w tiene forma (2,).
# Si transponemos x entonces tendrá la forma (3, 2) and se puede hacer broadcast
# contra w para producir un resultado de la forma (3, 2); transponiendo este resultado
# se produce el resultado final de la forma (2, 3) que es la matriz x con el
# vector w agregado a cada columna.

print (x)
print (w)
print ((x.T + w).T)

In [ ]:
# Otra solución es cambiar la forma de w a un vector fila de forma (2, 1);
# podemos entonces broadcastearlo contra x para producir la misma salida.
print (x + np.reshape(w, (2, 1)))

In [ ]:
# Multiplicar una matriz por una constante:
# x tiene forma (2, 3). Numpy trata escalares como arrays de forma ();
# estos pueden ser broadcasteados a la forma (2, 3), produciendo el
# siguiente array:
print (x * 2)

*Broadcasting* usualmente hace que el código sea más conciso y más rápido, así que úsenlo donde se pueda.

Para saber más de numpy, chequeen la [documentación oficial de numpy](http://docs.scipy.org/doc/numpy/reference/).

##Matplotlib

Matplotlib es una librería para graficar. En esta sección veremos una introducción al módulo `matplotlib.pyplot`.

In [ ]:
import matplotlib.pyplot as plt

Corriendo este comando especial de iPython, veremos los gráficos en el navegador del Jupyter notebook:

In [ ]:
%matplotlib inline

###Graficando

La función más importante en  `matplotlib` es plot, que permite graficar datos 2D. Ejemplo:

In [ ]:
# Computa las coordenadas x, y para los puntos en una curva seno
x = np.arange(0, 3 * np.pi, 0.1)
y = np.sin(x)

# Grafica los puntos usando matplotlib
plt.plot(x, y)

Con un poco de trabajo extra, podemos graficar múltiples funciones a la vez, y agregar un título, una leyenda, y nombre a los ejes:

In [ ]:
y_cos = np.cos(x)

# Grafica los puntos usando matplotlib
plt.plot(x, y)
plt.plot(x, y_cos)
plt.xlabel('Eje x')
plt.ylabel('Eje y')
plt.title('Seno y Coseno')
plt.legend(['Función Seno', 'Función Coseno'])

###Gráficos compuestos

Se pueden poner muchos gráficos en la misma figura usando la función subplot.

In [ ]:
# Computa las coordenadas x, y para puntos en las curvas seno y coseno
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Hace una grilla de gráficos compuestos que tiene altura 2 y ancho 1,
# y pone al primero de los subgráficos como activo.
plt.subplot(2, 1, 1)

# Dibuja el primer gráfico
plt.plot(x, y_sin)
plt.title('Seno')

# Pone como activo el segundo subgráfico, y hace el segundo dibujo.
plt.subplot(2, 1, 2)
plt.plot(x, y_cos)
plt.title('Coseno')

# Muestra el gráfico.
plt.show()

Para más detalles sobre la función `subplot` pueden leer la [documentación](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.subplot).